<?php
/**
 * Created by JetBrains PhpStorm.
 * User: michaelmclaughlin
 * Date: 3/27/12
 * Time: 9:43 AM
 * To change this template use File | Settings | File Templates.
 */

include 'BSSSQLConfig.php';
include 'BSSSQLOperation.php';


$FormName = $_GET['BSSFormName'];
$FormMode = $_GET['BSSFormMode'];


$CREATEMASTER  = "";
$READMASTER = "";
$UPDATEMASTER = "";
$DELETEMASTER = "";
$CREATECHILD = "";
$READCHILD = "";
$UPDATECHILD = "";
$DELETECHILD = "";
$CREATEWORKFLOW = "";
$ADDREMOVEAPPROVERS = "";
$PROMOTEWORKFLOW = "";
$SIGNOFF = "";
$READDOCUMENTS = "";
$ADDDOCUMENTS = "";
$UPDATEDOCUMENTS = "";
$DELETEDOCUMENTS = "";
$CHECKINCHECKOUT = "";
$GETDOCUMENTS = "";
$VIEWDISCUSSIONS = "";
$ADDDISCUSSIONS = "";
$UPDATEDISCUSSIONS = "";
$DELETEDISCUSSIONS = "";
$VIEWHISTORY = "";


//echo $FormMode;

mysql_connect(HOST, USERNAME, PASSWORD) or die(mysql_error());
mysql_select_db(DB) or die(mysql_error());

$result = mysql_query(
"SELECT
SUM(CREATEMASTER) AS CREATEMASTER,
SUM(READMASTER) AS READMASTER,
SUM(UPDATEMASTER) AS UPDATEMASTER,
SUM(DELETEMASTER) AS DELETEMASTER,
SUM(CREATECHILD) AS CREATECHILD,
SUM(READCHILD) AS READCHILD,
SUM(UPDATECHILD) AS UPDATECHILD,
SUM(DELETECHILD) AS DELETECHILD,
SUM(CREATEWORKFLOW) AS CREATEWORKFLOW,
SUM(ADDREMOVEAPPROVERS) AS ADDREMOVEAPPROVERS,
SUM(PROMOTEWORKFLOW) AS PROMOTEWORKFLOW,
SUM(SIGNOFF) AS SIGNOFF,
SUM(READDOCUMENTS) AS READDOCUMENTS,
SUM(ADDDOCUMENTS) AS ADDDOCUMENTS,
SUM(UPDATEDOCUMENTS) AS UPDATEDOCUMENTS,
SUM(DELETEDOCUMENTS) AS DELETEDOCUMENTS,
SUM(CHECKINCHECKOUT) AS CHECKINCHECKOUT,
SUM(GETDOCUMENTS) AS GETDOCUMENTS,
SUM(VIEWDISCUSSIONS) AS VIEWDISCUSSIONS,
SUM(ADDDISCUSSIONS) AS ADDDISCUSSIONS,
SUM(UPDATEDISCUSSIONS) AS UPDATEDISCUSSIONS,
SUM(DELETEDISCUSSIONS) AS DELETEDISCUSSIONS,
SUM(VIEWHISTORY) AS VIEWHISTORY" .  " FROM Roles "  .
"INNER JOIN UserRoles ON roleid = Roles.id
                AND UserRoles.masterid = 2
WHERE tableid = 2");






          $Y = 0;
          while ($row = mysql_fetch_assoc($result)){
             $Y = $Y + 1;
              $CREATEMASTER = $row["CREATEMASTER"];
              $READMASTER = $row["READMASTER"];
              $UPDATEMASTER = $row["UPDATEMASTER"];
              $DELETEMASTER = $row["DELETEMASTER"];
              $CREATECHILD = $row["CREATECHILD"];
              $READCHILD = $row["READCHILD"];
              $UPDATECHILD = $row["UPDATECHILD"];
              $DELETECHILD = $row["DELETECHILD"];
              $CREATEWORKFLOW = $row["CREATEWORKFLOW"];
              $ADDREMOVEAPPROVERS = $row["ADDREMOVEAPPROVERS"];
              $PROMOTEWORKFLOW = $row["PROMOTEWORKFLOW"];
              $SIGNOFF = $row["SIGNOFF"];
              $READDOCUMENTS = $row["READDOCUMENTS"];
              $ADDDOCUMENTS = $row["ADDDOCUMENTS"];
              $UPDATEDOCUMENTS = $row["UPDATEDOCUMENTS"];
              $DELETEDOCUMENTS = $row["DELETEDOCUMENTS"];
              $CHECKINCHECKOUT = $row["CHECKINCHECKOUT"];
              $GETDOCUMENTS = $row["GETDOCUMENTS"];
              $VIEWDISCUSSIONS = $row["VIEWDISCUSSIONS"];
              $ADDDISCUSSIONS = $row["ADDDISCUSSIONS"];
              $UPDATEDISCUSSIONS = $row["UPDATEDISCUSSIONS"];
              $DELETEDISCUSSIONS = $row["DELETEDISCUSSIONS"];
              $VIEWHISTORY = $row["VIEWHISTORY"];


          }

mysql_free_result($result);



$FormConfig =
'{"CREATEMASTER": "'. $CREATEMASTER . '",' .
'"READMASTER" :"' . $READMASTER . '",' .
'"UPDATEMASTER" :"' . $UPDATEMASTER . '",' .
'"DELETEMASTER" :"' . $DELETEMASTER . '",' .
'"CREATECHILD" :"' . $CREATECHILD . '",' .
'"READCHILD" :"' . $READCHILD . '",' .
'"UPDATECHILD" :"' . $UPDATECHILD . '",' .
'"DELETECHILD" :"' . $DELETECHILD . '",' .
'"CREATEWORKFLOW" :"' . $CREATEWORKFLOW . '",' .
'"ADDREMOVEAPPROVERS" :"' . $ADDREMOVEAPPROVERS . '",' .
'"PROMOTEWORKFLOW" :"' . $PROMOTEWORKFLOW . '",' .
'"SIGNOFF" :"' . $SIGNOFF . '",' .
'"READDOCUMENTS" :"' . $READDOCUMENTS . '",' .
'"ADDDOCUMENTS" :"' . $ADDDOCUMENTS . '",' .
'"UPDATEDOCUMENTS" :"' . $UPDATEDOCUMENTS . '",' .
'"DELETEDOCUMENTS" :"' . $DELETEDOCUMENTS . '",' .
'"CHECKINCHECKOUT" :"' . $CHECKINCHECKOUT . '",' .
'"GETDOCUMENTS" :"' . $DELETEDOCUMENTS . '",' .
'"VIEWDISCUSSIONS" :"' . $VIEWDISCUSSIONS . '",' .
'"ADDDISCUSSIONS" :"' . $ADDDISCUSSIONS . '",' .
'"UPDATEDISCUSSIONS" :"' . $UPDATEDISCUSSIONS . '",' .
'"DELETEDISCUSSIONS" :"' . $DELETEDISCUSSIONS . '",' .
'"VIEWHISTORY" :"' . $VIEWHISTORY . '"}';

echo $FormConfig;

